### ISSUE TITLE
GUI error in Linux Ubuntu 14.04

### ISSUE THREAD

**Issue by martinsimon88** [amirrezaw/automagic#1]
Hello,

keep getting following error when executing in Ubuntu:

Error in main_gui>runpreprocessbutton_Callback (line 665)
project.preprocess_all();

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in main_gui (line 61)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)main_gui('runpreprocessbutton_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

best regards,
Martin

**Comment by amirrezaw** [comment]
Hello Martin,

It shouldn't be a problem inherent in Linux, I just test the app on Linux and it works fine (Although the graphical dimensions are a bit unproportional ).

Could you please make sure that you are using the latest version ?
Also, does this happen when you start the app, or when you click on preprocessing? How do you start the app, by running the function main_gui or by installing the app ?

Best,
Amirreza
